version: "3.8"

services:
  backend:
    image: talking_legislation_backend:latest
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app

  frontend:
    image: talking_legislation_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
